export const Questions = [
    {
        question: "Firewall in computer is used for",
        optionA: "Security",
        optionB: "Data Transmission",
        optionC: "Authentication",
        optionD: "Monitoring",
        answer: "A",
    },
    {
        question: "Which of the following is not an operating system",
        optionA: "DOS",
        optionB: "Mac",
        optionC: "C",
        optionD: "Linux",
        answer: "C",
    },
    {
        question: "1024 bit is equal to how many byte",
        optionA: "1 Byte",
        optionB: "128 Byte",
        optionC: "32 Byte",
        optionD: "64 Byte",
        answer: "B",
    },
    {
        question: "Mac Operating System is developed by which company",
        optionA: "IBM",
        optionB: "Apple",
        optionC: "Microsoft",
        optionD: "Samsung",
        answer: "B",
    },
    {
        question: "What does HTML stand for?",
        optionA: "Hyper Trainer Marking Language",
        optionB: "Hyper Text Marketing Language",
        optionC: "Hyper Text Markup Language",
        optionD: "Hyper Text Markup Leveler",
        answer: "C",
    },
    {
        question: "Inside which HTML element do we put the JavaScript?",
        optionA: "<js>",
        optionB: "<scripting>",
        optionC: "<script>",
        optionD: "<javascript>",
        answer: "C",
    },
    {
        question: "How do you write `Hello World` in an alert box?",
        optionA: `alert("Hello World");`,
        optionB: `msgBox("Hello World");`,
        optionC: `msg("Hello World");`,
        optionD: `alertBox("Hello World");`,
        answer: "A",
    },
    {
        question: "How do you round the number 7.25, to the nearest integer?",
        optionA: "rnd(7.25)",
        optionB: "round(7.25)",
        optionC: "Math.rnd(7.25)",
        optionD: "Math.round(7.25)",
        answer: "D",
    },
    {
        question: "Which operator is used to assign a value to a variable?",
        optionA: "x",
        optionB: "*",
        optionC: "=",
        optionD: "-",
        answer: "C",
    },
    {
        question: `What is the correct syntax for referring to an external script called "xxx.js"?`,
        optionA: `<script src="xxx.js">`,
        optionB: `<script href="xxx.js">`,
        optionC: `<script name="xxx.js">`,
        optionD: "None of the above",
        answer: "A",
    }
]